FROM python:3.11
COPY ./docker/start.sh /start.sh
RUN chmod +x /start.sh
COPY ./docker/gunicorn_conf.py /gunicorn_conf.py
RUN python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN python3 -m pip install poetry && poetry config virtualenvs.create false
WORKDIR /app
COPY ./bot.py ./README.md ./pyproject.toml ./poetry.lock* /app/
RUN poetry install --only=main,docker
ADD src /app/src

# Bot
ENV APP_MODULE=bot:app
ENV HOST=0.0.0.0
CMD ["/start.sh"]
